name: Pull Request

on: [pull_request]

jobs:
  test-ubuntu-latest:
    name: Test Swift ${{ matrix.swift }} Ubuntu Latest
    strategy:
      matrix:
        swift: ["6.0", "6.0.1", "6.0.2"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: swift test -Xswiftc -warnings-as-errors -Xcc -Werror
